spring:
  profiles:
    active: prod
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.100.76:3306/hope
      username: root
      password: 123456
  jpa:
      hibernate:
        ddl-auto: none
      show-sql: true