spring:
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hope?characterEncoding=utf8&useSSL=false
      username: root
      password:
  jpa:
      hibernate:
        ddl-auto: none
      show-sql: true